version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USER=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
      - POSTGRESQL_PASSWORD=bitnami1234
    volumes:
      - /path/to/postgresql-persistence:/bitnami
  sonarqube:
    image: bitnami/sonarqube:latest
    depends_on:
      - postgresql
    ports:
      - '8000:9000'
    environment:
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /path/to/sonarqube-persistence:/bitnami
